name: Cleanup Workflow Runs

on:
  schedule:
    - cron: "0 3 */15 * *"   #每 15 天执行, 凌晨 3 点执行
  workflow_dispatch:      # 可手动执行

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1          # 删除超过 1 天的运行记录
          keep_minimum_runs: 1    # 每个 workflow 最少保留 1 条
